### ISSUE TITLE
Randomly consume all CPU ressources

### ISSUE THREAD

**Issue by LucsT** [hpcloud/npm-lazy-mirror#11]
My npm-lazy-mirror after few days is taking 100% of the CPU slot allowed.

When I restart it, everything became normal, and cpu use is not more few % (even under sollicitation)

Is anyone experiment the same issue?

I continue investigation

**Comment by jdpaton** [comment]
I did some v8 profiling using to debug this particular issue and found that the `setInterval` function `node_modules/lactate/lib/store/CacheItem.js:35` was being called essentially every tick because the value being passed to set interval was already being multiplied by Lactate and exceeded 32^2.

The behaviour of setInterval() when the signed integer overflows is to interpret it is '0' so for each item in the cache, a new additional function was being called every tick leading to the 100% CPU usage over time. Patch is incoming.

**Comment by LucsT** [comment]
Nice job.
I put the patch in testing right now
